services:
  nginx:
    image: nginx:latest
    container_name: nginx-download
    volumes:
      - ./files:/files
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "${EXPOSE_PORT}:80"
    networks:
      - nginx-net
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.10.0
    container_name: nginx-exporter
    restart: unless-stopped
    ports:
      - "9113:9113"
    command: -nginx.scrape-uri=http://nginx/metrics
  minio:
    image: minio/minio:RELEASE.2020-06-14T18-32-17Z
    container_name: minio
    volumes:
      - ./files:/export
    command: server /export
    restart: unless-stopped
    environment:
      MINIO_ACCESS_KEY: PFTTDKXLCSZLGEYE
      MINIO_SECRET_KEY: 7jC7YD22DaS8L3AQKW7yCDPl0UvXlXXj
    networks:
      - nginx-net

networks:
  nginx-net:
    driver: bridge

